arb-dir: lib/l10n
template-arb-file: app_en.arb  
output-localization-file: gallery_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: desiredFileName.txt
preferred-supported-locales:
  - en
  - ar
use-deferred-loading: true
