name: progres
description: A student portal application for university students.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.4.3
  flutter: "3.22.2"  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  form_validator: ^2.1.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  go_router: ^12.1.1
  calendar_view: ^1.4.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  flutter_dotenv: ^5.2.1

flutter:


  uses-material-design: true



