name: progres
description: A student portal application for university students.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: "3.22.3"  # Updated to latest stable version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  form_validator: ^2.1.1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  go_router: ^14.8.1
  calendar_view: ^1.4.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  flutter_dotenv: ^5.2.1

flutter:


  uses-material-design: true



