name: Flutter CI & Security

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force CI run even without code changes'
        required: false
        default: 'false'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      workflow_changed: ${{ steps.filter.outputs.workflows }}
      code_changed: ${{ steps.filter.outputs.code }}
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
            code:
              - 'lib/**'
              - 'test/**'
              - 'pubspec.yaml'
              
      - name: Determine if we should build
        id: check
        run: |
          if [[ "${{ github.event.inputs.force_run }}" == "true" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Force run requested. Will run build regardless of changes."
          elif [[ "${{ steps.filter.outputs.code }}" == "true" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Code changes detected. Will run build."
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
            echo "No code changes detected and no force run requested. Skipping build."
          fi

  security-check:
    needs: check-changes
    if: needs.check-changes.outputs.workflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Author Permissions
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Workflow files were changed in a pull request. Checking permissions for user: ${{ github.event.pull_request.user.login }}"
            
            # Check if user is the repository owner
            if [[ "${{ github.repository_owner }}" == "${{ github.event.pull_request.user.login }}" ]]; then
              echo "User is the repository owner and is authorized to modify workflow files"
            else
              echo "::error::User is not the repository owner"
              echo "::error::Only the repository owner can modify workflow files"
              exit 1
            fi
          else
            # For push events or manual workflow runs, we assume it's authorized
            echo "Changes made through direct push to master or manual workflow run"
            echo "Assuming changes are authorized"
          fi

  build:
    needs: [check-changes, security-check]
    if: |
      needs.check-changes.outputs.should_build == 'true' && 
      (needs.security-check.result == 'success' || (needs.security-check.result == 'skipped' && needs.check-changes.outputs.workflow_changed != 'true'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib/
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --dart-define=TEST_USERNAME=${{ secrets.TEST_USERNAME }} --dart-define=TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
        
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ✅ CI build completed successfully!
            The APK is available as an artifact in this workflow run.
            Download the APK from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          pr_number: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}