name: Protected Files Check

concurrency:
  group: pre-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/ci.yml'

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate Author Permissions
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} 
        run: |
          echo "Checking permissions for user: ${{ github.event.pull_request.user.login }}"
          
          # Check if PR author is the repository owner
          if [ "${{ github.repository_owner }}" = "${{ github.event.pull_request.user.login }}" ]; then
            echo "Author is the repository owner and is authorized to modify protected files"
          else
            echo "::error::User is not the repository owner"
            echo "::error::Only the repository owner can modify protected files"
            exit 1
          fi
