name: Protected Files Check

concurrency:
  group: pre-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/ci.yml'

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Validate Author Permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR author is in maintainers team using GitHub API
          IS_MAINTAINER=$(gh api /orgs/${{ github.repository_owner }}/teams/repo-maintainers/memberships/${{ github.event.pull_request.user.login }} --silent && echo 'true' || echo 'false')
          
          if [[ "$IS_MAINTAINER" == "false" ]]; then
            echo "::error::Protected files can only be modified by maintainers"
            echo "::error::Please contact a maintainer for assistance"
            exit 1
          fi
          
          echo "Author is authorized to modify protected files"
